/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as AppAnalyticsRouteImport } from './routes/_app.analytics'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppWebhooksRouteImport } from './routes/_app.webhooks'
import { Route as DocsIndexRouteImport } from './routes/docs.index'
import { Route as DocsSlugRouteImport } from './routes/docs.$slug'
import { Route as RawSlugRouteImport } from './routes/raw.$slug'
import { Route as XRidRouteImport } from './routes/x.$rid'
import { Route as AppProjectsIndexRouteImport } from './routes/_app.projects.index'
import { Route as AppProjectsIdRouteImport } from './routes/_app.projects.$id'
import { Route as AppProjectsNewRouteImport } from './routes/_app.projects.new'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiProxySlugRouteImport } from './routes/api/proxy.$slug'
import { Route as AppProjectsIdIndexRouteImport } from './routes/_app.projects.$id.index'
import { Route as AppProjectsIdAnalyticsRouteImport } from './routes/_app.projects.$id.analytics'
import { Route as AppProjectsIdEditRouteImport } from './routes/_app.projects.$id.edit'
import { Route as AppProjectsIdSettingsRouteImport } from './routes/_app.projects.$id.settings'
import { Route as AppProjectsIdVersionsRouteImport } from './routes/_app.projects.$id.versions'
import { Route as AppProjectsIdWebhooksRouteImport } from './routes/_app.projects.$id.webhooks'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppWebhooksRoute = AppWebhooksRouteImport.update({
  id: '/webhooks',
  path: '/webhooks',
  getParentRoute: () => AppRoute,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/docs/',
  path: '/docs/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsSlugRoute = DocsSlugRouteImport.update({
  id: '/docs/$slug',
  path: '/docs/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const RawSlugRoute = RawSlugRouteImport.update({
  id: '/raw/$slug',
  path: '/raw/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const XRidRoute = XRidRouteImport.update({
  id: '/x/$rid',
  path: '/x/$rid',
  getParentRoute: () => rootRouteImport,
} as any)
const AppProjectsIndexRoute = AppProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsIdRoute = AppProjectsIdRouteImport.update({
  id: '/projects/$id',
  path: '/projects/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsNewRoute = AppProjectsNewRouteImport.update({
  id: '/projects/new',
  path: '/projects/new',
  getParentRoute: () => AppRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProxySlugRoute = ApiProxySlugRouteImport.update({
  id: '/api/proxy/$slug',
  path: '/api/proxy/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AppProjectsIdIndexRoute = AppProjectsIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppProjectsIdRoute,
} as any)
const AppProjectsIdAnalyticsRoute = AppProjectsIdAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppProjectsIdRoute,
} as any)
const AppProjectsIdEditRoute = AppProjectsIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => AppProjectsIdRoute,
} as any)
const AppProjectsIdSettingsRoute = AppProjectsIdSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppProjectsIdRoute,
} as any)
const AppProjectsIdVersionsRoute = AppProjectsIdVersionsRouteImport.update({
  id: '/versions',
  path: '/versions',
  getParentRoute: () => AppProjectsIdRoute,
} as any)
const AppProjectsIdWebhooksRoute = AppProjectsIdWebhooksRouteImport.update({
  id: '/webhooks',
  path: '/webhooks',
  getParentRoute: () => AppProjectsIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/analytics': typeof AppAnalyticsRoute
  '/dashboard': typeof AppDashboardRoute
  '/settings': typeof AppSettingsRoute
  '/webhooks': typeof AppWebhooksRoute
  '/docs/$slug': typeof DocsSlugRoute
  '/raw/$slug': typeof RawSlugRoute
  '/x/$rid': typeof XRidRoute
  '/docs/': typeof DocsIndexRoute
  '/projects/$id': typeof AppProjectsIdRouteWithChildren
  '/projects/new': typeof AppProjectsNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/proxy/$slug': typeof ApiProxySlugRoute
  '/projects/': typeof AppProjectsIndexRoute
  '/projects/$id/analytics': typeof AppProjectsIdAnalyticsRoute
  '/projects/$id/edit': typeof AppProjectsIdEditRoute
  '/projects/$id/settings': typeof AppProjectsIdSettingsRoute
  '/projects/$id/versions': typeof AppProjectsIdVersionsRoute
  '/projects/$id/webhooks': typeof AppProjectsIdWebhooksRoute
  '/projects/$id/': typeof AppProjectsIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/analytics': typeof AppAnalyticsRoute
  '/dashboard': typeof AppDashboardRoute
  '/settings': typeof AppSettingsRoute
  '/webhooks': typeof AppWebhooksRoute
  '/docs/$slug': typeof DocsSlugRoute
  '/raw/$slug': typeof RawSlugRoute
  '/x/$rid': typeof XRidRoute
  '/docs': typeof DocsIndexRoute
  '/projects/new': typeof AppProjectsNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/proxy/$slug': typeof ApiProxySlugRoute
  '/projects': typeof AppProjectsIndexRoute
  '/projects/$id/analytics': typeof AppProjectsIdAnalyticsRoute
  '/projects/$id/edit': typeof AppProjectsIdEditRoute
  '/projects/$id/settings': typeof AppProjectsIdSettingsRoute
  '/projects/$id/versions': typeof AppProjectsIdVersionsRoute
  '/projects/$id/webhooks': typeof AppProjectsIdWebhooksRoute
  '/projects/$id': typeof AppProjectsIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_app/analytics': typeof AppAnalyticsRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/webhooks': typeof AppWebhooksRoute
  '/docs/$slug': typeof DocsSlugRoute
  '/raw/$slug': typeof RawSlugRoute
  '/x/$rid': typeof XRidRoute
  '/docs/': typeof DocsIndexRoute
  '/_app/projects/$id': typeof AppProjectsIdRouteWithChildren
  '/_app/projects/new': typeof AppProjectsNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/proxy/$slug': typeof ApiProxySlugRoute
  '/_app/projects/': typeof AppProjectsIndexRoute
  '/_app/projects/$id/analytics': typeof AppProjectsIdAnalyticsRoute
  '/_app/projects/$id/edit': typeof AppProjectsIdEditRoute
  '/_app/projects/$id/settings': typeof AppProjectsIdSettingsRoute
  '/_app/projects/$id/versions': typeof AppProjectsIdVersionsRoute
  '/_app/projects/$id/webhooks': typeof AppProjectsIdWebhooksRoute
  '/_app/projects/$id/': typeof AppProjectsIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/signup'
    | '/analytics'
    | '/dashboard'
    | '/settings'
    | '/webhooks'
    | '/docs/$slug'
    | '/raw/$slug'
    | '/x/$rid'
    | '/docs/'
    | '/projects/$id'
    | '/projects/new'
    | '/api/auth/$'
    | '/api/proxy/$slug'
    | '/projects/'
    | '/projects/$id/analytics'
    | '/projects/$id/edit'
    | '/projects/$id/settings'
    | '/projects/$id/versions'
    | '/projects/$id/webhooks'
    | '/projects/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/signup'
    | '/analytics'
    | '/dashboard'
    | '/settings'
    | '/webhooks'
    | '/docs/$slug'
    | '/raw/$slug'
    | '/x/$rid'
    | '/docs'
    | '/projects/new'
    | '/api/auth/$'
    | '/api/proxy/$slug'
    | '/projects'
    | '/projects/$id/analytics'
    | '/projects/$id/edit'
    | '/projects/$id/settings'
    | '/projects/$id/versions'
    | '/projects/$id/webhooks'
    | '/projects/$id'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/forgot-password'
    | '/login'
    | '/signup'
    | '/_app/analytics'
    | '/_app/dashboard'
    | '/_app/settings'
    | '/_app/webhooks'
    | '/docs/$slug'
    | '/raw/$slug'
    | '/x/$rid'
    | '/docs/'
    | '/_app/projects/$id'
    | '/_app/projects/new'
    | '/api/auth/$'
    | '/api/proxy/$slug'
    | '/_app/projects/'
    | '/_app/projects/$id/analytics'
    | '/_app/projects/$id/edit'
    | '/_app/projects/$id/settings'
    | '/_app/projects/$id/versions'
    | '/_app/projects/$id/webhooks'
    | '/_app/projects/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  DocsSlugRoute: typeof DocsSlugRoute
  RawSlugRoute: typeof RawSlugRoute
  XRidRoute: typeof XRidRoute
  DocsIndexRoute: typeof DocsIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiProxySlugRoute: typeof ApiProxySlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/analytics': {
      id: '/_app/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/webhooks': {
      id: '/_app/webhooks'
      path: '/webhooks'
      fullPath: '/webhooks'
      preLoaderRoute: typeof AppWebhooksRouteImport
      parentRoute: typeof AppRoute
    }
    '/docs/': {
      id: '/docs/'
      path: '/docs'
      fullPath: '/docs/'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/$slug': {
      id: '/docs/$slug'
      path: '/docs/$slug'
      fullPath: '/docs/$slug'
      preLoaderRoute: typeof DocsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/raw/$slug': {
      id: '/raw/$slug'
      path: '/raw/$slug'
      fullPath: '/raw/$slug'
      preLoaderRoute: typeof RawSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/x/$rid': {
      id: '/x/$rid'
      path: '/x/$rid'
      fullPath: '/x/$rid'
      preLoaderRoute: typeof XRidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/projects/': {
      id: '/_app/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof AppProjectsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects/$id': {
      id: '/_app/projects/$id'
      path: '/projects/$id'
      fullPath: '/projects/$id'
      preLoaderRoute: typeof AppProjectsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects/new': {
      id: '/_app/projects/new'
      path: '/projects/new'
      fullPath: '/projects/new'
      preLoaderRoute: typeof AppProjectsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/proxy/$slug': {
      id: '/api/proxy/$slug'
      path: '/api/proxy/$slug'
      fullPath: '/api/proxy/$slug'
      preLoaderRoute: typeof ApiProxySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/projects/$id/': {
      id: '/_app/projects/$id/'
      path: '/'
      fullPath: '/projects/$id/'
      preLoaderRoute: typeof AppProjectsIdIndexRouteImport
      parentRoute: typeof AppProjectsIdRoute
    }
    '/_app/projects/$id/analytics': {
      id: '/_app/projects/$id/analytics'
      path: '/analytics'
      fullPath: '/projects/$id/analytics'
      preLoaderRoute: typeof AppProjectsIdAnalyticsRouteImport
      parentRoute: typeof AppProjectsIdRoute
    }
    '/_app/projects/$id/edit': {
      id: '/_app/projects/$id/edit'
      path: '/edit'
      fullPath: '/projects/$id/edit'
      preLoaderRoute: typeof AppProjectsIdEditRouteImport
      parentRoute: typeof AppProjectsIdRoute
    }
    '/_app/projects/$id/settings': {
      id: '/_app/projects/$id/settings'
      path: '/settings'
      fullPath: '/projects/$id/settings'
      preLoaderRoute: typeof AppProjectsIdSettingsRouteImport
      parentRoute: typeof AppProjectsIdRoute
    }
    '/_app/projects/$id/versions': {
      id: '/_app/projects/$id/versions'
      path: '/versions'
      fullPath: '/projects/$id/versions'
      preLoaderRoute: typeof AppProjectsIdVersionsRouteImport
      parentRoute: typeof AppProjectsIdRoute
    }
    '/_app/projects/$id/webhooks': {
      id: '/_app/projects/$id/webhooks'
      path: '/webhooks'
      fullPath: '/projects/$id/webhooks'
      preLoaderRoute: typeof AppProjectsIdWebhooksRouteImport
      parentRoute: typeof AppProjectsIdRoute
    }
  }
}

interface AppProjectsIdRouteChildren {
  AppProjectsIdAnalyticsRoute: typeof AppProjectsIdAnalyticsRoute
  AppProjectsIdEditRoute: typeof AppProjectsIdEditRoute
  AppProjectsIdSettingsRoute: typeof AppProjectsIdSettingsRoute
  AppProjectsIdVersionsRoute: typeof AppProjectsIdVersionsRoute
  AppProjectsIdWebhooksRoute: typeof AppProjectsIdWebhooksRoute
  AppProjectsIdIndexRoute: typeof AppProjectsIdIndexRoute
}

const AppProjectsIdRouteChildren: AppProjectsIdRouteChildren = {
  AppProjectsIdAnalyticsRoute: AppProjectsIdAnalyticsRoute,
  AppProjectsIdEditRoute: AppProjectsIdEditRoute,
  AppProjectsIdSettingsRoute: AppProjectsIdSettingsRoute,
  AppProjectsIdVersionsRoute: AppProjectsIdVersionsRoute,
  AppProjectsIdWebhooksRoute: AppProjectsIdWebhooksRoute,
  AppProjectsIdIndexRoute: AppProjectsIdIndexRoute,
}

const AppProjectsIdRouteWithChildren = AppProjectsIdRoute._addFileChildren(
  AppProjectsIdRouteChildren,
)

interface AppRouteChildren {
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppWebhooksRoute: typeof AppWebhooksRoute
  AppProjectsIdRoute: typeof AppProjectsIdRouteWithChildren
  AppProjectsNewRoute: typeof AppProjectsNewRoute
  AppProjectsIndexRoute: typeof AppProjectsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppWebhooksRoute: AppWebhooksRoute,
  AppProjectsIdRoute: AppProjectsIdRouteWithChildren,
  AppProjectsNewRoute: AppProjectsNewRoute,
  AppProjectsIndexRoute: AppProjectsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  DocsSlugRoute: DocsSlugRoute,
  RawSlugRoute: RawSlugRoute,
  XRidRoute: XRidRoute,
  DocsIndexRoute: DocsIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiProxySlugRoute: ApiProxySlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
